--RBAC Part
CREATE TABLE Resource
(
	[ResourceId] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[ResourceName] VARCHAR(50) NOT NULL UNIQUE
)

CREATE TABLE Role
(
	[RoleId] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[RoleName] VARCHAR(50) NOT NULL UNIQUE
)

CREATE TABLE [User]
(
	UserId INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	UserName VARCHAR(50) NOT NULL UNIQUE,
	Password CHAR(64) NOT NULL,
	FirstName VARCHAR(50) NOT NULL,
	LastName VARCHAR(50) NOT NULL
)

CREATE TABLE ResourceRole 
(
	ResourceRoleId INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	ResourceId INT NOT NULL FOREIGN KEY REFERENCES Resource (ResourceId),
	RoleId INT NOT NULL FOREIGN KEY REFERENCES Role (RoleId),
	CanAdd BIT NOT NULL,
	CanView BIT NOT NULL,
	CanEdit BIT NOT NULL,
	CanDelete BIT NOT NULL
)

CREATE TABLE UserRole
(
	UserRoleId INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	UserId INT NOT NULL FOREIGN KEY REFERENCES [User](UserId),
	RoleId INT NOT NULL FOREIGN KEY REFERENCES Role(RoleId)
)

--PRODUCTION part
CREATE TABLE Project
(
	ProjectId INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	ProjectName VARCHAR(50) NOT NULL,
	ProjectDescription VARCHAR(500),
	ProjectDeadline DATETIME
)

CREATE TABLE ProjectUserRole 
(
	ProjectUserId INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	UserRoleId INT NOT NULL FOREIGN KEY REFERENCES UserRole(UserRoleId),
	ProjectId INT NOT NULL FOREIGN KEY REFERENCES Project(ProjectId)
)

CREATE TABLE Sprint
(
	SprintId INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	ProjectId INT NOT NULL FOREIGN KEY REFERENCES Project(ProjectId),
	SprintStart DATETIME NOT NULL,
	SpintEnd DATETIME NOT NULL
)

CREATE TABLE Task
(
	TaskId INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	SprintId INT FOREIGN KEY REFERENCES Sprint(SprintId),
	TaskName VARCHAR(100) NOT NULL,
	TaskDescription VARCHAR(300) NOT NULL,
	IsDone BIT NOT NULL
)

CREATE TABLE Test
(
	TestId INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	TaskId INT NOT NULL FOREIGN KEY REFERENCES Task(TaskId),
	[Status] VARCHAR(50)
)

CREATE TABLE Release
(
	ReleaseId INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	ProjectId INT NOT NULL FOREIGN KEY REFERENCES Project(ProjectId),
	ReleaseDate DATETIME NOT NULL,
	ReleaseName VARCHAR(100) NOT NULL,
	ReleaseDescription VARCHAR(300) NOT NULL,
	ServerName VARCHAR(50) NOT NULL
)