DELETE FROM Release;
DELETE FROM Test;
DELETE FROM Task;
DELETE FROM Sprint;
DELETE FROM ProjectUserRole;
DELETE FROM Project;

DELETE FROM UserRole;
DELETE FROM ResourceRole;
DELETE FROM [User];
DELETE FROM [Role];
DELETE FROM Resource;

DBCC CHECKIDENT ('Release', RESEED, 0);
DBCC CHECKIDENT ('Test', RESEED, 0);
DBCC CHECKIDENT ('Task', RESEED, 0);
DBCC CHECKIDENT ('Sprint', RESEED, 0);
DBCC CHECKIDENT ('ProjectUserRole', RESEED, 0);
DBCC CHECKIDENT ('Project', RESEED, 0);

DBCC CHECKIDENT ('UserRole', RESEED, 0);
DBCC CHECKIDENT ('ResourceRole', RESEED, 0);
DBCC CHECKIDENT ('[User]', RESEED, 0);
DBCC CHECKIDENT ('[Role]', RESEED, 0);
DBCC CHECKIDENT ('Resource', RESEED, 0);