DROP TABLE Release;
DROP TABLE Test;
DROP TABLE Task;
DROP TABLE Sprint;
DROP TABLE ProjectUserRole;
DROP TABLE Project;

DROP TABLE UserRole;
DROP TABLE ResourceRole;
DROP TABLE [User];
DROP TABLE [Role];
DROP TABLE Resource;